<a href="https://colab.research.google.com/github/irynabereziuk/Machine-learning/blob/main/%D0%9A%D0%BE%D0%BF%D1%96%D1%8F_%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%BD%D0%B8%D0%BA%D0%B0_%22%D0%A2%D1%80%D0%B5%D0%BD%D1%83%D0%B2%D0%B0%D0%BB%D1%8C%D0%BD%D0%B8%D0%B9_%D0%BD%D0%BE%D1%83%D1%82%D0%B1%D1%83%D0%BA_%D0%91%D0%B5%D1%80%D0%B5%D0%B7%D1%8E%D0%BA_%D0%9B%D0%B5%D0%BA%D1%86%D1%96%D1%8F_2_NumPy_2026_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Тренувальний ноутбук до лекції 2  
## NumPy: масиви, векторизація та лінійна алгебра для машинного навчання

Ноутбук повторює та закріплює приклади, розглянуті в лекції.  
Усі основні приклади можна виконувати послідовно зверху вниз.

**Мета:** навчитися працювати з `ndarray`, індексацією, `dtype`, векторизацією, broadcasting, агрегуванням, зміною форми масивів, генерацією випадкових даних і засобами `numpy.linalg`.


## 1. Імпорт NumPy та перевірка версії

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.1.3


## 2. Створення `ndarray`

`ndarray` — основна структура NumPy. Усі елементи масиву мають узгоджений тип даних `dtype`.


In [2]:
a = np.array([1, 2, 3, 4, 5], dtype=np.float64)

m = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype=np.int64)

print("Вектор a:")
print(a)

print("\nМатриця M:")
print(m)

Вектор a:
[1. 2. 3. 4. 5.]

Матриця M:
[[1 2 3]
 [4 5 6]]


### Основні атрибути масиву

In [3]:
print("shape:", m.shape)
print("ndim:", m.ndim)
print("size:", m.size)
print("dtype:", m.dtype)
print("itemsize:", m.itemsize)
print("nbytes:", m.nbytes)

shape: (2, 3)
ndim: 2
size: 6
dtype: int64
itemsize: 8
nbytes: 48


### Самостійно
Створіть матрицю розміру `(3, 4)` та перевірте її `shape`, `ndim`, `size`, `dtype` і `nbytes`.


In [4]:
# Ваш код
m = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
], dtype=np.int64)

print("\nМатриця:")
print(m)

print("shape:", m.shape)
print("ndim:", m.ndim)
print("size:", m.size)
print("dtype:", m.dtype)
print("itemsize:", m.itemsize)
print("nbytes:", m.nbytes)


Матриця:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape: (3, 4)
ndim: 2
size: 12
dtype: int64
itemsize: 8
nbytes: 96


## 3. Спеціальні функції створення масивів

In [5]:
a = np.array([1, 2, 3, 4])
zeros = np.zeros((2, 3), dtype=np.float32)
ones = np.ones((2, 3), dtype=np.int64)
full = np.full((2, 3), 7)
i = np.eye(4)

print("a =", a)
print("\nzeros =\n", zeros)
print("\nones =\n", ones)
print("\nfull =\n", full)
print("\nI =\n", i)

a = [1 2 3 4]

zeros =
 [[0. 0. 0.]
 [0. 0. 0.]]

ones =
 [[1 1 1]
 [1 1 1]]

full =
 [[7 7 7]
 [7 7 7]]

I =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### `arange` і `linspace`

In [6]:
x1 = np.arange(0, 1, 0.2)
x2 = np.linspace(0, 1, num=6)

print("arange:", x1)
print("linspace:", x2)

arange: [0.  0.2 0.4 0.6 0.8]
linspace: [0.  0.2 0.4 0.6 0.8 1. ]


`np.arange(start, stop, step)` зручний, коли задається крок.  
`np.linspace(start, stop, num)` зручний, коли потрібно отримати точно задану кількість рівновіддалених значень.


## 4. Типи даних `dtype`

In [7]:
x = np.array([1, 2, 3], dtype=np.int32)
y = x.astype(np.float32)

print("x.dtype:", x.dtype)
print("y.dtype:", y.dtype)

x.dtype: int32
y.dtype: float32


### Приклад змішаних типів

In [8]:
a = np.array([1, 2, 3], dtype=np.float32)
b = np.float64(0.5)
c = a + b

print(c)
print("dtype результату:", c.dtype)

[1.5 2.5 3.5]
dtype результату: float64


### Самостійно
Створіть масив типу `float64` і перетворіть його на `float32`. Порівняйте `itemsize` і `nbytes`.


In [9]:
# Ваш код
d = np.array([2.5, 4.0, 6.5, 8.0], dtype=np.float64)
t = d.astype(np.float32)

print("d:", d)
print("Тип:", d.dtype)
print("Розмір одного елемента:", d.itemsize)
print("Розмір масиву:", d.nbytes)

print("t:", t)
print("Тип:", t.dtype)
print("Розмір одного елемента:", t.itemsize)
print("Розмір масиву:", t.nbytes)

d: [2.5 4.  6.5 8. ]
Тип: float64
Розмір одного елемента: 8
Розмір масиву: 32
t: [2.5 4.  6.5 8. ]
Тип: float32
Розмір одного елемента: 4
Розмір масиву: 16


## 5. Індексація та зрізи

In [10]:
a = np.array([10, 20, 30, 40, 50])

print(a[0])
print(a[-1])
print(a[1:4])
print(a[::2])

m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("\nM[1, 1] =", m[1, 1])
print("M[1:, 1] =", m[1:, 1])
print("M[0, :2] =", m[0, :2])

10
50
[20 30 40]
[10 30 50]

M[1, 1] = 5
M[1:, 1] = [5 8]
M[0, :2] = [1 2]


### Булева індексація

In [11]:
scores = np.array([56, 82, 91, 47, 73])
mask = scores >= 60

print("mask:", mask)
print("scores[mask]:", scores[mask])

passed = scores[scores >= 60]
print("passed:", passed)

mask: [False  True  True False  True]
scores[mask]: [82 91 73]
passed: [82 91 73]


### Розширена (fancy) індексація

In [12]:
a = np.array([10, 20, 30, 40, 50])
idx = np.array([4, 0, 2])

print(a[idx])

[50 10 30]


### Самостійно
Із масиву `scores` виберіть лише значення від 70 до 90 включно.


In [13]:
# Ваш код
passed = scores[(scores >= 70) & (scores <= 90)]
print("passed:", passed)

passed: [82 73]


## 6. Представлення (`view`) та копія

In [14]:
a = np.array([1, 2, 3, 4, 5])

view = a[1:4]
view[0] = 99

print("Після зміни view:")
print("a =", a)
print("view =", view)

a = np.array([1, 2, 3, 4, 5])

copy = a[1:4].copy()
copy[0] = 99

print("\nПісля зміни copy:")
print("a =", a)
print("copy =", copy)

Після зміни view:
a = [ 1 99  3  4  5]
view = [99  3  4]

Після зміни copy:
a = [1 2 3 4 5]
copy = [99  3  4]


Базовий зріз часто повертає **view**, тому зміна зрізу може змінити вихідний масив.  
Якщо потрібні незалежні дані, використовуйте `.copy()`.


## 7. Векторизація та універсальні функції

In [15]:
values = [1, 2, 3, 4]

# Python
squared_loop = [x ** 2 for x in values]

# NumPy
a = np.array(values)
squared_numpy = a ** 2

print("Python:", squared_loop)
print("NumPy:", squared_numpy)

Python: [1, 4, 9, 16]
NumPy: [ 1  4  9 16]


### Поелементний і матричний добутки

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)
print("a * b =", a * b)
print("a @ b =", a @ b)

a + b = [5 7 9]
a * b = [ 4 10 18]
a @ b = 32


### Універсальні функції `ufunc`

In [17]:
x = np.array([1.0, 4.0, 9.0])

print("sqrt:", np.sqrt(x))
print("log:", np.log(x))
print("maximum:", np.maximum(x, 5.0))

sqrt: [1. 2. 3.]
log: [0.         1.38629436 2.19722458]
maximum: [5. 5. 9.]


## 8. Broadcasting

In [18]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

bias = np.array([10, 20, 30])

print("X.shape:", x.shape)
print("bias.shape:", bias.shape)
print("\nX + bias =\n", x + bias)

X.shape: (2, 3)
bias.shape: (3,)

X + bias =
 [[11 22 33]
 [14 25 36]]


### Стандартизація за стовпцями через broadcasting

In [19]:
x = np.array([
    [170., 65.],
    [180., 80.],
    [160., 55.]
])

mean =x.mean(axis=0)
std = x.std(axis=0)
x_scaled = (x - mean) / std

print("mean:", mean)
print("std:", std)
print("\nX_scaled =\n", x_scaled)

mean: [170.          66.66666667]
std: [ 8.16496581 10.27402334]

X_scaled =
 [[ 0.         -0.16222142]
 [ 1.22474487  1.29777137]
 [-1.22474487 -1.13554995]]


### Самостійно
До кожного стовпця матриці додайте різне число за допомогою broadcasting.


In [20]:
# Ваш код
f = np.array([ 0, 15])
print(x + f)

[[170.  80.]
 [180.  95.]
 [160.  70.]]


## 9. Агрегування та параметр `axis`

In [21]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("sum:", m.sum())
print("sum(axis=0):", m.sum(axis=0))
print("sum(axis=1):", m.sum(axis=1))
print("mean(axis=0):", m.mean(axis=0))

sum: 21
sum(axis=0): [5 7 9]
sum(axis=1): [ 6 15]
mean(axis=0): [2.5 3.5 4.5]


### Робота з `NaN`

In [22]:
x = np.array([10.0, np.nan, 30.0, 40.0])

print("np.mean(x):", np.mean(x))
print("np.nanmean(x):", np.nanmean(x))

np.mean(x): nan
np.nanmean(x): 26.666666666666668


Корисні агрегувальні функції: `sum`, `mean`, `median`, `std`, `var`, `min`, `max`, `argmin`, `argmax`, `quantile`, `percentile`.


## 10. Зміна форми масивів

In [23]:
a = np.arange(12)
m = a.reshape(3, 4)

print("M =\n", m)
print("\nM.T =\n", m.T)
print("\nravel:", m.ravel())
print("flatten:", m.flatten())

M =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

M.T =
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

ravel: [ 0  1  2  3  4  5  6  7  8  9 10 11]
flatten: [ 0  1  2  3  4  5  6  7  8  9 10 11]


### Додавання нової осі

In [24]:
x = np.array([1, 2, 3])

row = x[np.newaxis, :]
col = x[:, np.newaxis]

print("x.shape:", x.shape)
print("row.shape:", row.shape)
print("col.shape:", col.shape)


print("\nx =\n", x)
print("\nrow =\n", row)
print("\ncol =\n", col)

x.shape: (3,)
row.shape: (1, 3)
col.shape: (3, 1)

x =
 [1 2 3]

row =
 [[1 2 3]]

col =
 [[1]
 [2]
 [3]]


## 11. Об’єднання масивів

In [25]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("a\n", a)

print("b\n", b)

print("concatenate axis=0:\n", np.concatenate([a, b], axis=0))
print("\nconcatenate axis=1:\n", np.concatenate([a, b], axis=1))
print("\nvstack:\n", np.vstack([a, b]))
print("\nhstack:\n", np.hstack([a, b]))

a
 [[1 2]
 [3 4]]
b
 [[5 6]
 [7 8]]
concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]

vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack:
 [[1 2 5 6]
 [3 4 7 8]]


### `stack` створює нову вісь

In [26]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

s = np.stack([x, y], axis=0)

print(s)
print("shape:", s.shape)

[[1 2 3]
 [4 5 6]]
shape: (2, 3)


## 12. Випадкові числа: сучасний `Generator API`

In [27]:
rng = np.random.default_rng(seed=42)

uniform = rng.random(5)
normal = rng.normal(loc=0.0, scale=1.0, size=5)
integers = rng.integers(0, 10, size=5)

print("uniform:", uniform)
print("normal:", normal)
print("integers:", integers)

uniform: [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
normal: [-1.30217951  0.1278404  -0.31624259 -0.01680116 -0.85304393]
integers: [5 3 1 9 7]


### Перемішування та випадкова вибірка

In [28]:
rng = np.random.default_rng(123)

idx = np.arange(10)
rng.shuffle(idx)

sample = rng.choice(np.arange(100), size=5, replace=False)

print("shuffled idx:", idx)
print("sample:", sample)

shuffled idx: [7 4 0 2 1 5 6 8 3 9]
sample: [77 43 90 27 44]


### Самостійно
Згенеруйте:
- матрицю `(4, 3)` із нормального розподілу;
- 10 випадкових цілих чисел від 1 до 100;
- випадкову вибірку з 5 різних індексів із діапазону `0..19`.


In [29]:
# Ваш код
rng = np.random.default_rng()

matrix = rng.normal(0, 1, (4, 3))
nums = rng.integers(1, 101, 10)
indexes = rng.choice(20, 5, replace=False)

print("Матриця:", matrix)
print("Числа:", nums)
print("Індекси:", indexes)

Матриця: [[ 0.49275644  0.034919   -0.43242738]
 [ 1.15523153 -1.30234107  0.80892112]
 [ 2.85160666 -1.36532251 -0.68853125]
 [ 1.31335435  1.17054084 -0.29462059]]
Числа: [48 77 46 21 35 98 95 21 66 42]
Індекси: [10 16  2  7  4]


## 13. Лінійна алгебра

### Матричний добуток

In [30]:
a = np.array([
    [1, 2, 3],
    [0, 1, 2]
])

b = np.array([
    [ 1, 2],
    [ 0, 4],
    [-1, 0]
])

c = a @ b
print(c)

[[-2 10]
 [-2  4]]


### Діагональ, транспонування та визначник

In [31]:
a = np.array([
    [ 1.,  0., 3.],
    [-1., -1., 2.],
    [ 4.,  7., 2.]
])

print("diag:", np.diag(a))
print("\nA.T =\n", a.T)

det = np.linalg.det(a)
print("\ndet(A) =", det)
print("det близький до -25:", np.isclose(det, -25.0))

diag: [ 1. -1.  2.]

A.T =
 [[ 1. -1.  4.]
 [ 0. -1.  7.]
 [ 3.  2.  2.]]

det(A) = -24.999999999999996
det близький до -25: True


### Розв’язання системи `Ax = b`

In [32]:
a = np.array([
    [1.,  2.,  5.],
    [1., -1.,  3.],
    [3., -6., -1.]
])

b = np.array([-9., 2., 25.])

x = np.linalg.solve(a, b)

print("x =", x)
print("Перевірка A @ x ≈ b:", np.allclose(a @ x, b))

x = [ 2. -3. -1.]
Перевірка A @ x ≈ b: True


Для розв’язання системи не потрібно явно обчислювати `A⁻¹`.  
У числових обчисленнях перевага надається `np.linalg.solve(A, b)`.


### Метод найменших квадратів

In [33]:
x = np.array([
    [1., 1.],
    [1., 2.],
    [1., 3.],
    [1., 4.]
])

y = np.array([2.1, 3.9, 6.2, 8.1])

beta, residuals, rank, s = np.linalg.lstsq(x, y, rcond=None)

print("beta:", beta)
print("residuals:", residuals)
print("rank:", rank)
print("singular values:", s)

beta: [6.9423189e-16 2.0300000e+00]
residuals: [0.043]
rank: 2
singular values: [5.77937881 0.77380911]


### Власні значення та власні вектори

In [34]:
a = np.array([
    [2., 1.],
    [1., 2.]
])

values, vectors = np.linalg.eigh(a)

print("Власні значення:", values)
print("Власні вектори:\n", vectors)

Власні значення: [1. 3.]
Власні вектори:
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


### SVD

In [35]:
a = np.array([
    [3., 1.],
    [1., 3.],
    [1., 1.]
])

U, s, Vt = np.linalg.svd(a, full_matrices=False)

print("U =\n", U)
print("\ns =", s)
print("\nVt =\n", Vt)

U =
 [[-6.66666667e-01  7.07106781e-01]
 [-6.66666667e-01 -7.07106781e-01]
 [-3.33333333e-01  5.92577380e-18]]

s = [4.24264069 2.        ]

Vt =
 [[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]


## 14. NumPy у задачах машинного навчання

### 14.1. Стандартизація ознак

In [36]:
x = np.array([
    [170., 65., 25.],
    [180., 80., 31.],
    [160., 55., 22.],
    [175., 72., 28.]
])

mu = x.mean(axis=0)
sigma = x.std(axis=0)
x_std = (x - mu) / sigma

print("Середні після стандартизації:")
print(x_std.mean(axis=0))

print("\nСтандартні відхилення:")
print(x_std.std(axis=0))

Середні після стандартизації:
[0.00000000e+00 0.00000000e+00 1.38777878e-17]

Стандартні відхилення:
[1. 1. 1.]


### 14.2. Лінійна модель без циклу

In [37]:
x = np.array([
    [1.0, 2.0],
    [2.0, 1.0],
    [3.0, 4.0]
])

w = np.array([0.5, -0.25])
b = 1.0

y_pred = x @ w + b

print(y_pred)

[1.   1.75 1.5 ]


### 14.3. Середньоквадратична помилка

In [38]:
y_true = np.array([1.2, 1.8, 2.5])
y_pred = np.array([1.0, 2.0, 2.3])

mse = np.mean((y_true - y_pred) ** 2)

print("MSE =", mse)

MSE = 0.04000000000000001


### 14.4. Евклідова відстань до набору об’єктів

In [39]:
x = np.array([
    [1., 2.],
    [4., 6.],
    [2., 3.]
])

q = np.array([1., 1.])

distances = np.linalg.norm(x - q, axis=1)

print(distances)

[1.         5.83095189 2.23606798]


## 15. Сортування, пошук і вибір

In [40]:
x = np.array([7, 2, 9, 2, 5])

print("sort:", np.sort(x))
print("argsort:", np.argsort(x))
print("unique:", np.unique(x))
print("where x >= 5:", np.where(x >= 5))
print("clip 3..7:", np.clip(x, 3, 7))

sort: [2 2 5 7 9]
argsort: [1 3 4 0 2]
unique: [2 5 7 9]
where x >= 5: (array([0, 2, 4]),)
clip 3..7: [7 3 7 3 5]


## 16. Збереження та завантаження масивів

In [41]:
x = np.arange(12).reshape(3, 4)

np.save("X.npy", x)
x_loaded = np.load("X.npy")

print("X_loaded.shape:", x_loaded.shape)
print(x_loaded)

np.savez_compressed(
    "dataset.npz",
    X=x,
    y=np.array([0, 1, 1])
)

data = np.load("dataset.npz")
print("\ndata['X'] =\n", data["X"])
print("data['y'] =", data["y"])

X_loaded.shape: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

data['X'] =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
data['y'] = [0 1 1]


## 17. Числова стабільність і перевірка даних

In [42]:
x = np.array([1.0, np.nan, np.inf, -5.0])

print("isfinite:", np.isfinite(x))
print("Скінченні значення:", x[np.isfinite(x)])

isfinite: [ True False False  True]
Скінченні значення: [ 1. -5.]


### Порівняння чисел із плаваючою комою

In [43]:
a = 0.1 + 0.2
b = 0.3
print("a ", a)

print("a == b:", a == b)
print("np.isclose(a, b):", np.isclose(a, b))

a  0.30000000000000004
a == b: False
np.isclose(a, b): True


## 18. Узагальнюючий приклад: підготовка даних і лінійний прогноз

In [44]:
# 1. Вхідні дані: два фактори та цільова змінна
x = np.array([
    [10., 2.],
    [12., 3.],
    [15., 4.],
    [18., 5.],
    [20., 6.]
])

y = np.array([21., 25., 31., 36., 40.])

# 2. Фільтрація
mask = np.isfinite(x).all(axis=1) & np.isfinite(y)
x = x[mask]
y = y[mask]

# 3. Стандартизація ознак
mu = x.mean(axis=0)
sigma = x.std(axis=0)
x_std = (x - mu) / sigma

# 4. Додаємо стовпець одиниць для вільного члена
x_design = np.column_stack([
    np.ones(x_std.shape[0]),
    x_std
])

# 5. Оцінювання параметрів методом найменших квадратів
beta, *_ = np.linalg.lstsq(x_design, y, rcond=None)

# 6. Прогноз і MSE
y_pred = x_design @ beta
mse = np.mean((y - y_pred) ** 2)

print("beta =", beta)
print("y_pred =", y_pred)
print("MSE =", mse)

beta = [30.6         5.53172667  1.41421356]
y_pred = [21.1 25.1 30.6 36.1 40.1]
MSE = 0.03999999999999986


## 19. Підсумкові тренувальні завдання

1. Створіть матрицю `X` форми `(5, 4)` із випадкових чисел.
2. Обчисліть середнє та стандартне відхилення кожної ознаки.
3. Стандартизуйте матрицю через broadcasting.
4. Виберіть рядки, у яких значення першої ознаки додатне.
5. Додайте до матриці новий стовпець одиниць.
6. Створіть вектор ваг і обчисліть прогноз `X @ w`.
7. Для заданого `y_true` обчисліть MSE.
8. Перевірте, чи немає в масивах `NaN` або `inf`.


In [45]:
#1
X = rng.normal(loc=0.0, scale=1.0, size=(5, 4))

print("X =")
print(X)
print("shape:", X.shape)

#2
mean = X.mean(axis=0)
std = X.std(axis=0)

print("\nСереднє кожної ознаки:")
print(mean)

print("\nСтандартне відхилення кожної ознаки:")
print(std)

#3
X_std = (X - mean) / std

print("\nСтандартизована матриця X_std:")
print(X_std)

print("\nСередні після стандартизації:")
print(X_std.mean(axis=0))

print("\nСтандартні відхилення після стандартизації:")
print(X_std.std(axis=0))

#4
mask = X[:, 0] > 0
X_positive = X[mask]

print("\nМаска:")
print(mask)

print("\nРядки, де перша ознака додатна:")
print(X_positive)

#5
X_with_ones = np.column_stack([
    X,
    np.ones(X.shape[0])
])

print("\nX з додатковим стовпцем одиниць:")
print(X_with_ones)

#6
w = np.array([0.5, -0.25, 0.8, 0.3])

y_pred = X @ w

print("\nВектор ваг:")
print(w)

print("\nПрогноз X @ w:")
print(y_pred)

#7
y_true = np.array([0.5, -0.2, 1.0, 0.3, -0.7])

mse = np.mean((y_true - y_pred) ** 2)

print("\ny_true:")
print(y_true)

print("\nMSE =", mse)

#8
print("\nПеревірка X:")
print("Є NaN:", np.isnan(X).any())
print("Є inf:", np.isinf(X).any())
print("Усі значення скінченні:", np.isfinite(X).all())

print("\nПеревірка y_true:")
print("Є NaN:", np.isnan(y_true).any())
print("Є inf:", np.isinf(y_true).any())
print("Усі значення скінченні:", np.isfinite(y_true).all())

X =
[[ 0.69282645  1.30029842 -0.54992204  0.86798187]
 [-0.44920536  0.18711355  0.59797178  1.01679592]
 [ 0.67338887 -0.25267339  0.50197062 -1.57792578]
 [ 0.43352392 -0.96152811 -0.109264    0.50518737]
 [-1.33827488  1.33926292 -0.21245578  2.08415936]]
shape: (5, 4)

Середнє кожної ознаки:
[0.0024518  0.32249468 0.04566012 0.57923975]

Стандартне відхилення кожної ознаки:
[0.78919441 0.89305976 0.4378609  1.19987144]

Стандартизована матриця X_std:
[[ 0.87478401  1.09489172 -1.36020858  0.24064422]
 [-0.57230152 -0.15159246  1.26138612  0.36466921]
 [ 0.85015436 -0.64404208  1.04213576 -1.79783055]
 [ 0.54621791 -1.43777924 -0.3538204  -0.06171693]
 [-1.69885475  1.13852206 -0.5894929   1.25423405]]

Середні після стандартизації:
[ 4.4408921e-17  4.4408921e-17 -4.4408921e-17 -8.8817842e-17]

Стандартні відхилення після стандартизації:
[1. 1. 1. 1.]

Маска:
[ True False  True  True False]

Рядки, де перша ознака додатна:
[[ 0.69282645  1.30029842 -0.54992204  0.86798187]
 [ 0.673

## Контрольні запитання

1. Чим `ndarray` відрізняється від списку Python?
2. Що означають `shape`, `ndim`, `size`, `dtype`, `itemsize`?
3. У чому різниця між `np.arange` і `np.linspace`?
4. Чим `view` відрізняється від `copy`?
5. Що таке векторизація?
6. Які правила broadcasting?
7. Як трактувати `axis=0` і `axis=1`?
8. Чим відрізняються `*` та `@`?
9. Чому для `Ax=b` краще використовувати `np.linalg.solve`?
10. Чому для нового коду рекомендовано `np.random.default_rng()`?
